version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: my_wob_app:lzw_web
    # container_name: flask_app
    ports:
      - "6070:6000"
    volumes:
      - ./:/app
    depends_on:
      - mysql
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: 123456
    #   MYSQL_DB: diary_db
    # restart: always
    command: python lzwtest2.py
    networks:
      - net  

  mysql:
    image: mysql:latest
    # container_name: mysql_db
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: diary_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    networks:
      - net  

networks:
  net:
    driver: bridge
